apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: kube-diff-logger
  name: kube-diff-logger
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      name: kube-diff-logger
  template:
    metadata:
      labels:
        name: kube-diff-logger
    spec:
      containers:
      - name: kube-diff-logger
        command:
        - ./differ
        - -config=/etc/kube-diff-logger/config.yml
        image: muandane/differ:0.0.1
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 50m
            memory: 50Mi
        ports:
        - containerPort: 2112
          name: metrics
        volumeMounts:
        - mountPath: /etc/kube-diff-logger
          name: kube-diff-logger
      serviceAccountName: kube-diff-logger
      volumes:
      - configMap:
          name: kube-diff-logger
        name: kube-diff-logger
---
apiVersion: v1
kind: Service
metadata:
  name: kube-diff-logger
spec:
  selector:
    name: kube-diff-logger
  ports:
  - port: 2112
    targetPort: metrics
